-- 코드를 입력하세요
SELECT USED_GOODS_BOARD.TITLE,USED_GOODS_REPLY.BOARD_ID,USED_GOODS_REPLY.REPLY_ID,USED_GOODS_REPLY.WRITER_ID,USED_GOODS_REPLY.CONTENTS,date_format(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
from USED_GOODS_BOARD
    inner join USED_GOODS_REPLY
    on USED_GOODS_BOARD.board_id = USED_GOODS_REPLY.board_id
where month(USED_GOODS_BOARD.CREATED_DATE)=10
order by USED_GOODS_REPLY.created_date, USED_GOODS_BOARD.title
